name: .NET

on:
  push:
    branches: [ master ]
    paths:
    - 'apis/poi/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'apis/poi/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: ./apis/poi
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET      
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore	  
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: openhackkv74imm5acr.azurecr.io
        username: ${{ secrets.REPOSITORY_OWNER }}
        password: ${{ secrets.ACR_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: devopsoh/api-poi:build2
        file: /apis/poi/web/Dockerfile

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
        
    - name: Logging to Azure Boards on failure
      uses: stefanstranger/azuredevops-bug-action@1.1  
      if: failure()
      with:
          OrganizationName: "SuperSix"
          PAT: "PAT"
          ProjectName: "SuperSixInsurance"
          AreaPath: "SuperSixInsurance\\DeploymentArea"
          IterationPath: "SuperSixInsurance"
          GithubToken: "GithubToken"
          WorkflowFileName: "dotnet.yml"
      env:
            PAT: ${{ secrets.PAT}}
            GithubToken: ${{ secrets.githubtoken}}
