name: Go

on:
  push:
    branches: [ master ]
    paths:
    - 'apis/trips/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'apis/trips/**'

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apis/trips
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./

    - name: Test
      run: go test -v ./
